# Created using wingetcreate 0.4.3.1
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.0.0.schema.json

PackageIdentifier: LinwoodCloud.Butterfly
PackageVersion: 1.0
PackageLocale: en-US
Publisher: LinwoodCloud
PackageName: Butterfly
License: GPL-3.0
ShortDescription: Butterfly is a note app where your ideas come first. You can paint, add texts and export them easily on every device.
ManifestType: defaultLocale
ManifestVersion: 1.0.0

