# Created using wingetcreate 1.0.4.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.1.0.schema.json

PackageIdentifier: LinwoodCloud.Butterfly.Nightly
PackageVersion: 1.3.0-rc.0
Installers:
- Architecture: neutral
  InstallerType: inno
  InstallerUrl: https://github.com/LinwoodCloud/Butterfly/releases/download/v1.3.0-rc.0/Butterfly-Setup.exe
  InstallerSha256: FDEE3B73C91A2123885D46EBCFCFB85C59838AD5CE593B3A246B8B634932A2C8
ManifestType: installer
ManifestVersion: 1.1.0

